// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PcBuilderBackend.Domain.Enums;
using PcBuilderBackend.Infrastructure.Persistence;

#nullable disable

namespace PcBuilderBackend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PcBuilderDbContext))]
    [Migration("20260718090613_UpdateBaseEntity")]
    partial class UpdateBaseEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ddr_generation", new[] { "ddr4", "ddr5" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "m2_form_factor", new[] { "m22230", "m22242", "m22260", "m22280", "m222110" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "mb_form_factor", new[] { "mitx", "matx", "atx", "eatx" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pcie_generation", new[] { "gen3", "gen4", "gen5", "gen6" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pcie_slot_lane", new[] { "x1", "x4", "x8", "x16" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pcie_slot_type", new[] { "x1", "x4", "x8", "x16" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "psu_cable_type", new[] { "motherboard24pin", "cpu4plus4pin", "pcie6plus2pin", "pcie12v_high_power", "pcie12v2x6", "sata", "molex", "floppy" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "psu_form_factor", new[] { "flex_atx", "tfx", "sfx", "sfx_l", "atx" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "psu_modularity", new[] { "non_modular", "semi_modular", "full_modular" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ram_form_factor", new[] { "u_dimm", "so_dimm" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Chassis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("HeightMm")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("LengthMm")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<double>("MaxCpuCoolerHeightMm")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxGraphicsCardLengthMm")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxPsuLengthMm")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.PrimitiveCollection<List<MbFormFactor>>("SupportedMbFormFactors")
                        .IsRequired()
                        .HasColumnType("mb_form_factor[]");

                    b.PrimitiveCollection<List<PsuFormFactor>>("SupportedPsuFormFactors")
                        .IsRequired()
                        .HasColumnType("psu_form_factor[]");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("WidthMm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Chassis");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisDriveBay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BayCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChassisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DriveBayFormFactor")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChassisId");

                    b.ToTable("ChassisDriveBays");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisFan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiameterMm")
                        .HasColumnType("integer");

                    b.Property<int>("FansCountPerPack")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("ChassisFans");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisFanMount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChassisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Location")
                        .HasColumnType("integer");

                    b.Property<bool>("SingleDiameterOnly")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChassisId");

                    b.ToTable("ChassisFanMounts");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisFanMountOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChassisFanMountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Diameter")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SlotCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChassisFanMountId");

                    b.ToTable("ChassisFanMountOptions");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisPcieSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChassisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LowProfileSlots")
                        .HasColumnType("boolean");

                    b.Property<int>("Orientation")
                        .HasColumnType("integer");

                    b.Property<int>("SlotCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChassisId");

                    b.ToTable("ChassisPcieSlots");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisRadiator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChassisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<int>("MountLocation")
                        .HasColumnType("integer");

                    b.Property<int>("RadiatorCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChassisId");

                    b.ToTable("ChassisRadiators");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Chipset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SocketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SocketId");

                    b.ToTable("Chipsets");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Cpu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DdrGeneration>("DdrGeneration")
                        .HasColumnType("ddr_generation");

                    b.Property<bool>("IncludedStockCooler")
                        .HasColumnType("boolean");

                    b.Property<bool>("IntegratedGraphics")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxMemoryGb")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SocketId")
                        .HasColumnType("uuid");

                    b.Property<int>("ThermalDesignPower")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SocketId");

                    b.ToTable("Cpus");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.CpuCooler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .HasColumnType("uuid");

                    b.Property<double?>("CoolerHeightMm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<double?>("MaxRamHeightMm")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxTdp")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RadiatorLength")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("CpuCoolers");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.CpuCoolerSocket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CpuCoolerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SocketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CpuCoolerId");

                    b.HasIndex("SocketId");

                    b.ToTable("CpuCoolerSockets");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Gpu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Gpus");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.GraphicsCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GpuId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LengthMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<PcieGeneration>("PcieGeneration")
                        .HasColumnType("pcie_generation");

                    b.Property<int>("PcieSlotsUsed")
                        .HasColumnType("integer");

                    b.Property<decimal>("PowerConsumptionWatts")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VideoMemoryGb")
                        .HasColumnType("integer");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("GpuId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("GraphicsCards");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.GraphicsCardPowerConnector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .HasColumnType("uuid");

                    b.Property<int>("ConnectorCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GraphicsCardId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<PsuCableType>("PsuCableType")
                        .HasColumnType("psu_cable_type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GraphicsCardId");

                    b.ToTable("GraphicsCardPowerConnectors");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Motherboard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BluetoothEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ChipsetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DdrGeneration>("DdrGeneration")
                        .HasColumnType("ddr_generation");

                    b.Property<int>("EpsConnectors")
                        .HasColumnType("integer");

                    b.Property<int>("FanConnectors")
                        .HasColumnType("integer");

                    b.Property<MbFormFactor>("FormFactor")
                        .HasColumnType("mb_form_factor");

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxDimmSizeGb")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMemoryGb")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<RamFormFactor>("RamFormFactor")
                        .HasColumnType("ram_form_factor");

                    b.Property<int>("RamSlots")
                        .HasColumnType("integer");

                    b.Property<int>("SataPorts")
                        .HasColumnType("integer");

                    b.Property<Guid>("SocketId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<int>>("SupportedMemorySpeeds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<bool>("WifiEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ChipsetId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SocketId");

                    b.ToTable("Motherboards");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.MotherboardM2", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<M2FormFactor>>("FormFactors")
                        .IsRequired()
                        .HasColumnType("m2_form_factor[]");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MotherboardId")
                        .HasColumnType("uuid");

                    b.Property<PcieGeneration>("PcieGeneration")
                        .HasColumnType("pcie_generation");

                    b.Property<int>("SlotCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MotherboardId");

                    b.ToTable("MotherboardM2Slots");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.MotherboardPcie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<PcieGeneration>("Generation")
                        .HasColumnType("pcie_generation");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MotherboardId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotCount")
                        .HasColumnType("integer");

                    b.Property<PcieSlotLane>("SlotLanes")
                        .HasColumnType("pcie_slot_lane");

                    b.Property<PcieSlotType>("SlotType")
                        .HasColumnType("pcie_slot_type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MotherboardId");

                    b.ToTable("MotherboardPcieSlots");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Psu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<PsuFormFactor>("FormFactor")
                        .HasColumnType("psu_form_factor");

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LengthMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<PsuModularity>("Modularity")
                        .HasColumnType("psu_modularity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wattage")
                        .HasColumnType("integer");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Psus");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.PsuCable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CablesCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<int>("ConnectorsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PsuId")
                        .HasColumnType("uuid");

                    b.Property<PsuCableType>("Type")
                        .HasColumnType("psu_cable_type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PsuId");

                    b.ToTable("PsuCables");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Ram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DdrGeneration>("DdrGeneration")
                        .HasColumnType("ddr_generation");

                    b.Property<double>("HeightMm")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxMemorySpeedMts")
                        .HasColumnType("integer");

                    b.Property<int>("MemorySizePerStickGb")
                        .HasColumnType("integer");

                    b.Property<int>("ModulesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<RamFormFactor>("RamFormFactor")
                        .HasColumnType("ram_form_factor");

                    b.Property<int>("TotalMemorySizeGb")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Rams");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Socket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Sockets");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.StorageDrive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CapacityGb")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConcurrencyToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FormFactor")
                        .HasColumnType("integer");

                    b.Property<int>("Interface")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Media")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<PcieGeneration?>("PcieGeneration")
                        .HasColumnType("pcie_generation");

                    b.Property<int?>("Rpm")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("StorageDrives");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.WiredNetworkAdapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HostInterface")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxSpeedMbps")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("WiredNetworkAdapters");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.WirelessNetworkAdapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BluetoothVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConcurrencyToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HostInterface")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxSpeedMbps")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxSpeedMbps5G")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxSpeedMbps6G")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WifiStandard")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("WirelessNetworkAdapters");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Chassis", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Chassis")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisDriveBay", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Chassis", null)
                        .WithMany("DriveBays")
                        .HasForeignKey("ChassisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisFan", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("ChassisFans")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisFanMount", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Chassis", null)
                        .WithMany("FanMounts")
                        .HasForeignKey("ChassisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisFanMountOption", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.ChassisFanMount", null)
                        .WithMany("Options")
                        .HasForeignKey("ChassisFanMountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisPcieSlot", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Chassis", null)
                        .WithMany("PcieSlots")
                        .HasForeignKey("ChassisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisRadiator", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Chassis", null)
                        .WithMany("Radiators")
                        .HasForeignKey("ChassisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Chipset", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Chipsets")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.Socket", "Socket")
                        .WithMany()
                        .HasForeignKey("SocketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Socket");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Cpu", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Cpus")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.Socket", "Socket")
                        .WithMany("Cpus")
                        .HasForeignKey("SocketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Socket");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.CpuCooler", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("CpuCoolers")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.CpuCoolerSocket", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.CpuCooler", "CpuCooler")
                        .WithMany()
                        .HasForeignKey("CpuCoolerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.Socket", "Socket")
                        .WithMany()
                        .HasForeignKey("SocketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CpuCooler");

                    b.Navigation("Socket");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Gpu", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", null)
                        .WithMany("Gpus")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.GraphicsCard", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Gpu", "Gpu")
                        .WithMany()
                        .HasForeignKey("GpuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("GraphicsCards")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gpu");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.GraphicsCardPowerConnector", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.GraphicsCard", null)
                        .WithMany("PowerConnectors")
                        .HasForeignKey("GraphicsCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Motherboard", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Chipset", "Chipset")
                        .WithMany("Motherboards")
                        .HasForeignKey("ChipsetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Motherboards")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.Socket", "Socket")
                        .WithMany("Motherboards")
                        .HasForeignKey("SocketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chipset");

                    b.Navigation("Manufacturer");

                    b.Navigation("Socket");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.MotherboardM2", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Motherboard", null)
                        .WithMany("M2Slots")
                        .HasForeignKey("MotherboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.MotherboardPcie", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Motherboard", null)
                        .WithMany("PcieSlots")
                        .HasForeignKey("MotherboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Psu", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Psus")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.PsuCable", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Psu", null)
                        .WithMany("Cables")
                        .HasForeignKey("PsuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Ram", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Rams")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Socket", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Sockets")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.StorageDrive", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("StorageDrives")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.WiredNetworkAdapter", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("WiredNetworkAdapters")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.WirelessNetworkAdapter", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("WirelessNetworkAdapters")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Chassis", b =>
                {
                    b.Navigation("DriveBays");

                    b.Navigation("FanMounts");

                    b.Navigation("PcieSlots");

                    b.Navigation("Radiators");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisFanMount", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Chipset", b =>
                {
                    b.Navigation("Motherboards");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.GraphicsCard", b =>
                {
                    b.Navigation("PowerConnectors");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Manufacturer", b =>
                {
                    b.Navigation("Chassis");

                    b.Navigation("ChassisFans");

                    b.Navigation("Chipsets");

                    b.Navigation("CpuCoolers");

                    b.Navigation("Cpus");

                    b.Navigation("Gpus");

                    b.Navigation("GraphicsCards");

                    b.Navigation("Motherboards");

                    b.Navigation("Psus");

                    b.Navigation("Rams");

                    b.Navigation("Sockets");

                    b.Navigation("StorageDrives");

                    b.Navigation("WiredNetworkAdapters");

                    b.Navigation("WirelessNetworkAdapters");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Motherboard", b =>
                {
                    b.Navigation("M2Slots");

                    b.Navigation("PcieSlots");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Psu", b =>
                {
                    b.Navigation("Cables");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Socket", b =>
                {
                    b.Navigation("Cpus");

                    b.Navigation("Motherboards");
                });
#pragma warning restore 612, 618
        }
    }
}
