// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PcBuilderBackend.Domain.Enums;
using PcBuilderBackend.Infrastructure.Persistence;

#nullable disable

namespace PcBuilderBackend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PcBuilderDbContext))]
    [Migration("20260709063353_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ddr_generation", new[] { "ddr4", "ddr5" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "mb_form_factor", new[] { "mitx", "matx", "atx", "eatx" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pcie_generation", new[] { "gen3", "gen4", "gen5", "gen6" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pcie_slot_lane", new[] { "x1", "x4", "x8", "x16" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pcie_slot_type", new[] { "x1", "x4", "x8", "x16" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "psu_cable_type", new[] { "motherboard24pin", "cpu4plus4pin", "pcie6plus2pin", "pcie12v_high_power", "pcie12v2x6", "sata", "molex", "floppy" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "psu_form_factor", new[] { "flex_atx", "tfx", "sfx", "sfx_l", "atx" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "psu_modularity", new[] { "non_modular", "semi_modular", "full_modular" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ram_form_factor", new[] { "u_dimm", "so_dimm" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Chipset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Chipsets");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Cpu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxMemoryGb")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SocketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SocketId");

                    b.ToTable("Cpus");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Gpu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Gpus");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.GraphicsCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GpuId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("LengthMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<PcieGeneration>("PcieGeneration")
                        .HasColumnType("pcie_generation");

                    b.Property<int>("PcieSlots")
                        .HasColumnType("integer");

                    b.Property<decimal>("PowerConsumptionWatts")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VideoMemory")
                        .HasColumnType("integer");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("GpuId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("GraphicsCards");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Motherboard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChipsetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DdrGeneration>("DdrGeneration")
                        .HasColumnType("ddr_generation");

                    b.Property<int>("FanConnectors")
                        .HasColumnType("integer");

                    b.Property<MbFormFactor>("FormFactor")
                        .HasColumnType("mb_form_factor");

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxDimmSizeGb")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMemoryGb")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<RamFormFactor>("RamFormFactor")
                        .HasColumnType("ram_form_factor");

                    b.Property<int>("RamSlots")
                        .HasColumnType("integer");

                    b.Property<int>("SataPorts")
                        .HasColumnType("integer");

                    b.Property<Guid>("SocketId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<int>>("SupportedMemorySpeeds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("ChipsetId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SocketId");

                    b.ToTable("Motherboards");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.MotherboardM2", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MotherboardId")
                        .HasColumnType("uuid");

                    b.Property<PcieGeneration>("PcieGeneration")
                        .HasColumnType("pcie_generation");

                    b.Property<int>("SlotCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MotherboardId");

                    b.ToTable("MotherboardM2Slots");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.MotherboardPcie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<PcieGeneration>("Generation")
                        .HasColumnType("pcie_generation");

                    b.Property<Guid>("MotherboardId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotCount")
                        .HasColumnType("integer");

                    b.Property<PcieSlotLane>("SlotLanes")
                        .HasColumnType("pcie_slot_lane");

                    b.Property<PcieSlotType>("SlotType")
                        .HasColumnType("pcie_slot_type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MotherboardId");

                    b.ToTable("MotherboardPcieSlots");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Psu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<PsuFormFactor>("FormFactor")
                        .HasColumnType("psu_form_factor");

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("LengthMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<PsuModularity>("Modularity")
                        .HasColumnType("psu_modularity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wattage")
                        .HasColumnType("integer");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Psus");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.PsuCable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CablesCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<int>("ConnectorsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PsuId")
                        .HasColumnType("uuid");

                    b.Property<PsuCableType>("Type")
                        .HasColumnType("psu_cable_type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PsuId");

                    b.ToTable("PsuCables");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Ram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DdrGeneration>("DdrGeneration")
                        .HasColumnType("ddr_generation");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxMemorySpeedMts")
                        .HasColumnType("integer");

                    b.Property<int>("MemorySizePerStickGb")
                        .HasColumnType("integer");

                    b.Property<int>("ModulesCount")
                        .HasColumnType("integer");

                    b.Property<RamFormFactor>("RamFormFactor")
                        .HasColumnType("ram_form_factor");

                    b.Property<int>("TotalMemorySize")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Rams");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Socket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Sockets");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Chipset", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", null)
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Cpu", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Cpus")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.Socket", "Socket")
                        .WithMany("Cpus")
                        .HasForeignKey("SocketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Socket");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Gpu", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", null)
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.GraphicsCard", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Gpu", "Gpu")
                        .WithMany()
                        .HasForeignKey("GpuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gpu");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Motherboard", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Chipset", "Chipset")
                        .WithMany("Motherboards")
                        .HasForeignKey("ChipsetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.Socket", "Socket")
                        .WithMany("Motherboards")
                        .HasForeignKey("SocketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chipset");

                    b.Navigation("Manufacturer");

                    b.Navigation("Socket");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.MotherboardM2", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Motherboard", null)
                        .WithMany("M2Slots")
                        .HasForeignKey("MotherboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.MotherboardPcie", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Motherboard", null)
                        .WithMany("PcieSlots")
                        .HasForeignKey("MotherboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Psu", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", null)
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.PsuCable", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Psu", null)
                        .WithMany("Cables")
                        .HasForeignKey("PsuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Ram", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Socket", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Sockets")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Chipset", b =>
                {
                    b.Navigation("Motherboards");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Manufacturer", b =>
                {
                    b.Navigation("Cpus");

                    b.Navigation("Sockets");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Motherboard", b =>
                {
                    b.Navigation("M2Slots");

                    b.Navigation("PcieSlots");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Psu", b =>
                {
                    b.Navigation("Cables");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Socket", b =>
                {
                    b.Navigation("Cpus");

                    b.Navigation("Motherboards");
                });
#pragma warning restore 612, 618
        }
    }
}
