// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PcBuilderBackend.Domain.Enums;
using PcBuilderBackend.Infrastructure.Persistence;

#nullable disable

namespace PcBuilderBackend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PcBuilderDbContext))]
    [Migration("20260727150012_AddChildAggregateUniqueConstraints")]
    partial class AddChildAggregateUniqueConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "bluetooth_version", new[] { "v5point0", "v5point1", "v5point2", "v5point3", "v5point4" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "cpu_cooler_type", new[] { "air", "water" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ddr_generation", new[] { "ddr4", "ddr5" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "drive_bay_form_factor", new[] { "inch25", "inch35", "inch525" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fan_diameter_mm", new[] { "mm80", "mm92", "mm120", "mm140", "mm200" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fan_mount_location", new[] { "front", "top", "bottom", "rear", "sides" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "m2_form_factor", new[] { "m22230", "m22242", "m22260", "m22280", "m222110" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "mb_form_factor", new[] { "mitx", "matx", "atx", "eatx" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pcie_generation", new[] { "gen3", "gen4", "gen5", "gen6" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pcie_orientation", new[] { "vertical", "horizontal" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pcie_slot_lane", new[] { "x1", "x4", "x8", "x16" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "pcie_slot_type", new[] { "x1", "x4", "x8", "x16" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "psu_cable_type", new[] { "motherboard24pin", "cpu4plus4pin", "pcie6plus2pin", "pcie12v_high_power", "pcie12v2x6", "sata", "molex", "floppy" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "psu_form_factor", new[] { "flex_atx", "tfx", "sfx", "sfx_l", "atx" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "psu_modularity", new[] { "non_modular", "semi_modular", "full_modular" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "radiator_length", new[] { "mm120", "mm140", "mm240", "mm280", "mm360", "mm420" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "radiator_mount_location", new[] { "front", "top", "bottom", "rear", "sides" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ram_form_factor", new[] { "u_dimm", "so_dimm" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ram_rank", new[] { "single_rank", "dual_rank" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "storage_form_factor", new[] { "m22230", "m22242", "m22260", "m22280", "m222110", "sata25", "sata35" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "storage_interface", new[] { "sata", "nvme" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "storage_media", new[] { "hdd", "ssd" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "wifi_standard", new[] { "wifi4", "wifi5", "wifi6", "wifi6e", "wifi7" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "wired_host_interface", new[] { "pcie", "usb" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "wireless_host_interface", new[] { "m2", "pcie", "usb" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Chassis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("HeightMm")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("LengthMm")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<double>("MaxCpuCoolerHeightMm")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxGraphicsCardLengthMm")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxPsuLengthMm")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("WidthMm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Chassis");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisDriveBay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("BayCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ChassisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DriveBayFormFactor>("DriveBayFormFactor")
                        .HasColumnType("drive_bay_form_factor");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChassisId", "DriveBayFormFactor")
                        .IsUnique();

                    b.ToTable("ChassisDriveBays");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisFan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<FanDiameterMm>("DiameterMm")
                        .HasColumnType("fan_diameter_mm");

                    b.Property<int>("FansCountPerPack")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("ChassisFans");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisFanMount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChassisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<FanMountLocation>("Location")
                        .HasColumnType("fan_mount_location");

                    b.Property<bool>("SingleDiameterOnly")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChassisId", "Location")
                        .IsUnique();

                    b.ToTable("ChassisFanMounts");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisFanMountOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChassisFanMountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<FanDiameterMm>("Diameter")
                        .HasColumnType("fan_diameter_mm");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("SlotCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChassisFanMountId", "Diameter")
                        .IsUnique();

                    b.ToTable("ChassisFanMountOptions");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisMbFormFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChassisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<MbFormFactor>("MbFormFactor")
                        .HasColumnType("mb_form_factor");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChassisId", "MbFormFactor")
                        .IsUnique();

                    b.ToTable("ChassisMbFormFactor");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisPcieSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChassisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LowProfileSlots")
                        .HasColumnType("boolean");

                    b.Property<PcieOrientation>("Orientation")
                        .HasColumnType("pcie_orientation");

                    b.Property<int>("SlotCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChassisId", "LowProfileSlots", "Orientation")
                        .IsUnique();

                    b.ToTable("ChassisPcieSlots");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisPsuFormFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChassisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<PsuFormFactor>("PsuFormFactor")
                        .HasColumnType("psu_form_factor");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChassisId", "PsuFormFactor")
                        .IsUnique();

                    b.ToTable("ChassisPsuFormFactor");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisRadiator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChassisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<RadiatorLength>("Length")
                        .HasColumnType("radiator_length");

                    b.Property<RadiatorMountLocation>("MountLocation")
                        .HasColumnType("radiator_mount_location");

                    b.Property<int>("RadiatorCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChassisId", "Length", "MountLocation")
                        .IsUnique();

                    b.ToTable("ChassisRadiators");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Chipset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SocketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SocketId");

                    b.ToTable("Chipsets");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Cpu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DdrGeneration>("DdrGeneration")
                        .HasColumnType("ddr_generation");

                    b.Property<bool>("IncludedStockCooler")
                        .HasColumnType("boolean");

                    b.Property<bool>("IntegratedGraphics")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxMemoryGb")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SocketId")
                        .HasColumnType("uuid");

                    b.Property<int>("ThermalDesignPower")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("SocketId");

                    b.ToTable("Cpus");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.CpuCooler", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<double?>("CoolerHeightMm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<double?>("MaxRamHeightMm")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxTdp")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<RadiatorLength?>("RadiatorLength")
                        .HasColumnType("radiator_length");

                    b.Property<CpuCoolerType>("Type")
                        .HasColumnType("cpu_cooler_type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("CpuCoolers");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.CpuCoolerSocket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CpuCoolerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SocketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SocketId");

                    b.HasIndex("CpuCoolerId", "SocketId")
                        .IsUnique();

                    b.ToTable("CpuCoolerSockets");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.CpuRamMaxSpeed", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CpuId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxSpeedMts")
                        .HasColumnType("integer");

                    b.Property<int>("RamModuleCount")
                        .HasColumnType("integer");

                    b.Property<RamRank>("RamRank")
                        .HasColumnType("ram_rank");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CpuId", "RamModuleCount", "RamRank")
                        .IsUnique();

                    b.ToTable("CpuRamMaxSpeeds");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.CpuSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SocketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SocketId");

                    b.ToTable("CpuSeries");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Gpu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Gpus");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.GpuSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("GpuSeries");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.GraphicsCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GpuId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LengthMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<PcieGeneration>("PcieGeneration")
                        .HasColumnType("pcie_generation");

                    b.Property<int>("PcieSlotsUsed")
                        .HasColumnType("integer");

                    b.Property<decimal>("PowerConsumptionWatts")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VideoMemoryGb")
                        .HasColumnType("integer");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("GpuId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("GraphicsCards");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.GraphicsCardPowerConnector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<int>("ConnectorCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GraphicsCardId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<PsuCableType>("PsuCableType")
                        .HasColumnType("psu_cable_type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GraphicsCardId", "PsuCableType")
                        .IsUnique();

                    b.ToTable("GraphicsCardPowerConnectors");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Manufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Motherboard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BluetoothEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ChipsetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DdrGeneration>("DdrGeneration")
                        .HasColumnType("ddr_generation");

                    b.Property<int>("EpsConnectors")
                        .HasColumnType("integer");

                    b.Property<int>("FanConnectors")
                        .HasColumnType("integer");

                    b.Property<MbFormFactor>("FormFactor")
                        .HasColumnType("mb_form_factor");

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxDimmSizeGb")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMemoryGb")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<RamFormFactor>("RamFormFactor")
                        .HasColumnType("ram_form_factor");

                    b.Property<int>("RamSlots")
                        .HasColumnType("integer");

                    b.Property<int>("SataPorts")
                        .HasColumnType("integer");

                    b.Property<Guid>("SocketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<bool>("WifiEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ChipsetId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("SocketId");

                    b.ToTable("Motherboards");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.MotherboardM2", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MotherboardId")
                        .HasColumnType("uuid");

                    b.Property<PcieGeneration>("PcieGeneration")
                        .HasColumnType("pcie_generation");

                    b.Property<int>("SlotCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MotherboardId", "PcieGeneration")
                        .IsUnique();

                    b.ToTable("MotherboardM2Slots");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.MotherboardM2FormFactor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<M2FormFactor>("FormFactor")
                        .HasColumnType("m2_form_factor");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MotherboardM2Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MotherboardM2Id", "FormFactor")
                        .IsUnique();

                    b.ToTable("MotherboardM2FormFactors");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.MotherboardPcie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<PcieGeneration>("Generation")
                        .HasColumnType("pcie_generation");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MotherboardId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotCount")
                        .HasColumnType("integer");

                    b.Property<PcieSlotLane>("SlotLanes")
                        .HasColumnType("pcie_slot_lane");

                    b.Property<PcieSlotType>("SlotType")
                        .HasColumnType("pcie_slot_type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MotherboardId", "SlotType", "SlotLanes", "Generation")
                        .IsUnique();

                    b.ToTable("MotherboardPcieSlots");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Psu", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<PsuFormFactor>("FormFactor")
                        .HasColumnType("psu_form_factor");

                    b.Property<decimal>("HeightMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LengthMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<PsuModularity>("Modularity")
                        .HasColumnType("psu_modularity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wattage")
                        .HasColumnType("integer");

                    b.Property<decimal>("WidthMm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Psus");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.PsuCable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CablesCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<int>("ConnectorsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PsuId")
                        .HasColumnType("uuid");

                    b.Property<PsuCableType>("Type")
                        .HasColumnType("psu_cable_type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PsuId", "Type")
                        .IsUnique();

                    b.ToTable("PsuCables");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Ram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DdrGeneration>("DdrGeneration")
                        .HasColumnType("ddr_generation");

                    b.Property<double>("HeightMm")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxMemorySpeedMts")
                        .HasColumnType("integer");

                    b.Property<int>("MemorySizePerStickGb")
                        .HasColumnType("integer");

                    b.Property<int>("ModulesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<RamFormFactor>("RamFormFactor")
                        .HasColumnType("ram_form_factor");

                    b.Property<RamRank>("RamRank")
                        .HasColumnType("ram_rank");

                    b.Property<int>("TotalMemorySizeGb")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Rams");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Socket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Sockets");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.StorageDrive", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CapacityGb")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<StorageFormFactor>("FormFactor")
                        .HasColumnType("storage_form_factor");

                    b.Property<StorageInterface>("Interface")
                        .HasColumnType("storage_interface");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<StorageMedia>("Media")
                        .HasColumnType("storage_media");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<PcieGeneration?>("PcieGeneration")
                        .HasColumnType("pcie_generation");

                    b.Property<int?>("Rpm")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("StorageDrives");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.WiredNetworkAdapter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<WiredHostInterface>("HostInterface")
                        .HasColumnType("wired_host_interface");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxSpeedMbps")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("WiredNetworkAdapters");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.WirelessNetworkAdapter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<BluetoothVersion?>("BluetoothVersion")
                        .HasColumnType("bluetooth_version");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<WirelessHostInterface>("HostInterface")
                        .HasColumnType("wireless_host_interface");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxSpeedMbps")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxSpeedMbps5G")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxSpeedMbps6G")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<WifiStandard>("WifiStandard")
                        .HasColumnType("wifi_standard");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("WirelessNetworkAdapters");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Chassis", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Chassis")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisDriveBay", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Chassis", "Chassis")
                        .WithMany("DriveBays")
                        .HasForeignKey("ChassisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chassis");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisFan", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("ChassisFans")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisFanMount", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Chassis", "Chassis")
                        .WithMany("FanMounts")
                        .HasForeignKey("ChassisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chassis");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisFanMountOption", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.ChassisFanMount", "Mount")
                        .WithMany("Options")
                        .HasForeignKey("ChassisFanMountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mount");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisMbFormFactor", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Chassis", "Chassis")
                        .WithMany("MbFormFactors")
                        .HasForeignKey("ChassisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chassis");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisPcieSlot", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Chassis", "Chassis")
                        .WithMany("PcieSlots")
                        .HasForeignKey("ChassisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chassis");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisPsuFormFactor", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Chassis", "Chassis")
                        .WithMany("PsuFormFactors")
                        .HasForeignKey("ChassisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chassis");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisRadiator", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Chassis", "Chassis")
                        .WithMany("Radiators")
                        .HasForeignKey("ChassisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chassis");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Chipset", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Chipsets")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.Socket", "Socket")
                        .WithMany()
                        .HasForeignKey("SocketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Socket");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Cpu", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Cpus")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.CpuSeries", "Series")
                        .WithMany("Cpu")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.Socket", "Socket")
                        .WithMany("Cpus")
                        .HasForeignKey("SocketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Series");

                    b.Navigation("Socket");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.CpuCooler", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("CpuCoolers")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.CpuCoolerSocket", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.CpuCooler", "CpuCooler")
                        .WithMany("CpuCoolerSockets")
                        .HasForeignKey("CpuCoolerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.Socket", "Socket")
                        .WithMany("CpuCoolerSockets")
                        .HasForeignKey("SocketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CpuCooler");

                    b.Navigation("Socket");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.CpuRamMaxSpeed", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Cpu", "Cpu")
                        .WithMany("RamMaxSpeeds")
                        .HasForeignKey("CpuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cpu");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.CpuSeries", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("CpuSeries")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.Socket", "Socket")
                        .WithMany()
                        .HasForeignKey("SocketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Socket");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Gpu", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Gpus")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.GpuSeries", "Series")
                        .WithMany("Gpus")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.GpuSeries", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("GpuSeries")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.GraphicsCard", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Gpu", "Gpu")
                        .WithMany()
                        .HasForeignKey("GpuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("GraphicsCards")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gpu");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.GraphicsCardPowerConnector", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.GraphicsCard", null)
                        .WithMany("PowerConnectors")
                        .HasForeignKey("GraphicsCardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Motherboard", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Chipset", "Chipset")
                        .WithMany("Motherboards")
                        .HasForeignKey("ChipsetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Motherboards")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PcBuilderBackend.Domain.Entities.Socket", "Socket")
                        .WithMany("Motherboards")
                        .HasForeignKey("SocketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chipset");

                    b.Navigation("Manufacturer");

                    b.Navigation("Socket");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.MotherboardM2", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Motherboard", null)
                        .WithMany("M2Slots")
                        .HasForeignKey("MotherboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.MotherboardM2FormFactor", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.MotherboardM2", "MotherboardM2")
                        .WithMany("FormFactors")
                        .HasForeignKey("MotherboardM2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MotherboardM2");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.MotherboardPcie", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Motherboard", null)
                        .WithMany("PcieSlots")
                        .HasForeignKey("MotherboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Psu", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Psus")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.PsuCable", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Psu", null)
                        .WithMany("Cables")
                        .HasForeignKey("PsuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Ram", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Rams")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Socket", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Sockets")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.StorageDrive", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("StorageDrives")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.WiredNetworkAdapter", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("WiredNetworkAdapters")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.WirelessNetworkAdapter", b =>
                {
                    b.HasOne("PcBuilderBackend.Domain.Entities.Manufacturer", "Manufacturer")
                        .WithMany("WirelessNetworkAdapters")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Chassis", b =>
                {
                    b.Navigation("DriveBays");

                    b.Navigation("FanMounts");

                    b.Navigation("MbFormFactors");

                    b.Navigation("PcieSlots");

                    b.Navigation("PsuFormFactors");

                    b.Navigation("Radiators");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.ChassisFanMount", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Chipset", b =>
                {
                    b.Navigation("Motherboards");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Cpu", b =>
                {
                    b.Navigation("RamMaxSpeeds");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.CpuCooler", b =>
                {
                    b.Navigation("CpuCoolerSockets");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.CpuSeries", b =>
                {
                    b.Navigation("Cpu");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.GpuSeries", b =>
                {
                    b.Navigation("Gpus");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.GraphicsCard", b =>
                {
                    b.Navigation("PowerConnectors");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Manufacturer", b =>
                {
                    b.Navigation("Chassis");

                    b.Navigation("ChassisFans");

                    b.Navigation("Chipsets");

                    b.Navigation("CpuCoolers");

                    b.Navigation("CpuSeries");

                    b.Navigation("Cpus");

                    b.Navigation("GpuSeries");

                    b.Navigation("Gpus");

                    b.Navigation("GraphicsCards");

                    b.Navigation("Motherboards");

                    b.Navigation("Psus");

                    b.Navigation("Rams");

                    b.Navigation("Sockets");

                    b.Navigation("StorageDrives");

                    b.Navigation("WiredNetworkAdapters");

                    b.Navigation("WirelessNetworkAdapters");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Motherboard", b =>
                {
                    b.Navigation("M2Slots");

                    b.Navigation("PcieSlots");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.MotherboardM2", b =>
                {
                    b.Navigation("FormFactors");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Psu", b =>
                {
                    b.Navigation("Cables");
                });

            modelBuilder.Entity("PcBuilderBackend.Domain.Entities.Socket", b =>
                {
                    b.Navigation("CpuCoolerSockets");

                    b.Navigation("Cpus");

                    b.Navigation("Motherboards");
                });
#pragma warning restore 612, 618
        }
    }
}
